apiVersion: tempo.grafana.com/v1alpha1
kind: TempoStack
metadata:
  annotations:
    tempo.grafana.com/cert-hash-tempo-tempostack-compactor-mtls: 0d1876fcac036eb1f01399b87b9ffcd3747705f5b4c79ffe99bb6abed2fd492f
    tempo.grafana.com/cert-hash-tempo-tempostack-distributor-mtls: 902489fd06a2f7818878549e379970e3c0e7c7ec528f9b83015f36de0565c2b9
    tempo.grafana.com/cert-hash-tempo-tempostack-gateway-mtls: f2b2f41192894de356e194aea45988214eff621a8cbb210bdba8c88e64714520
    tempo.grafana.com/cert-hash-tempo-tempostack-ingester-mtls: 42a81f924ee453ee0fe93b75b34d673fc52d4b60a4f2cdaf282217d912cb010c
    tempo.grafana.com/cert-hash-tempo-tempostack-querier-mtls: 0aecf1450c117f0a3fdbe3a8c64457978b1cd9163a1502543d909a35d000f8e6
    tempo.grafana.com/cert-hash-tempo-tempostack-query-frontend-mtls: 041e3ba32a30c30a5bd94786ccde9bbdcb1f4e04961a614499abe16e88f7823b
  creationTimestamp: "2026-01-08T05:25:06Z"
  finalizers:
  - tempo.grafana.com/finalizer
  generation: 1
  labels:
    app.kubernetes.io/managed-by: tempo-operator
    tempo-perf-test.io/instance: tempo-perf-medium
    tempo-perf-test.io/managed-by: framework
    tempo.grafana.com/distribution: openshift
  name: tempostack
  namespace: tempo-perf-medium
  resourceVersion: "544070"
  uid: ac7b2e37-50b3-49c0-8eb6-cc833a3ed16d
spec:
  extraConfig:
    tempo:
      ingester:
        max_block_duration: 10m
  hashRing:
    memberlist: {}
  images: {}
  limits:
    global:
      ingestion:
        maxTracesPerUser: 0
      query:
        maxSearchDuration: 0s
  managementState: Managed
  observability:
    grafana:
      instanceSelector: {}
    metrics:
      createPrometheusRules: true
      createServiceMonitors: true
    tracing:
      jaeger_agent_endpoint: localhost:6831
      otlp_http_endpoint: http://localhost:4320
  replicationFactor: 1
  resources: {}
  retention:
    global:
      traces: 48h0m0s
  search:
    defaultResultLimit: 20
    maxDuration: 0s
  serviceAccount: tempo-tempostack
  storage:
    secret:
      name: minio
      type: s3
    tls:
      enabled: false
  storageSize: 10Gi
  template:
    compactor:
      replicas: 1
    distributor:
      component:
        replicas: 1
      tls:
        enabled: false
    gateway:
      component:
        replicas: 1
      enabled: true
      ingress:
        route:
          termination: reencrypt
        type: route
      rbac:
        enabled: false
    ingester:
      replicas: 1
    querier:
      replicas: 1
    queryFrontend:
      component:
        replicas: 1
      jaegerQuery:
        enabled: true
        ingress:
          route: {}
        monitorTab:
          enabled: false
          prometheusEndpoint: ""
        servicesQueryDuration: 72h0m0s
        tempoQuery: {}
  tenants:
    authentication:
    - tenantId: tenant-1
      tenantName: tenant-1
    mode: openshift
  timeout: 30s
status:
  components:
    compactor:
      Running:
      - tempo-tempostack-compactor-7fd5f94454-ldskp
      - tempo-tempostack-compactor-65bb84ccf-4h58w
    distributor:
      Running:
      - tempo-tempostack-distributor-fc99d9c68-pr9kd
    gateway:
      Running:
      - tempo-tempostack-gateway-849cb9b9f4-gltkt
    ingester:
      Running:
      - tempo-tempostack-ingester-0
    querier:
      Running:
      - tempo-tempostack-querier-855886d987-8vfgk
    queryFrontend:
      Running:
      - tempo-tempostack-query-frontend-858fdb8664-fm88w
  conditions:
  - lastTransitionTime: "2026-01-08T05:26:21Z"
    message: Some Tempo components are pending on dependencies
    reason: PendingComponents
    status: "False"
    type: Pending
  - lastTransitionTime: "2026-01-08T05:26:21Z"
    message: 'built in cert manager error: failed to add certificate hash annotations:
      Operation cannot be fulfilled on tempostacks.tempo.grafana.com "tempostack":
      the object has been modified; please apply your changes to the latest version
      and try again'
    reason: FailedReconciliation
    status: "False"
    type: Failed
  - lastTransitionTime: "2026-01-08T05:26:21Z"
    message: All components are operational
    reason: Ready
    status: "True"
    type: Ready
  operatorVersion: 0.19.0
  tempoVersion: 2.9.0
