apiVersion: tempo.grafana.com/v1alpha1
kind: TempoStack
metadata:
  annotations:
    tempo.grafana.com/cert-hash-tempo-tempostack-compactor-mtls: c1ffb0721bb42c0b0b955157d90f0df6a6910c18a728bb49ffc784db96b8bf13
    tempo.grafana.com/cert-hash-tempo-tempostack-distributor-mtls: 0d671dab8c10ff8b0c2fe811357850f0dd9709867c12a389b350432324c2549e
    tempo.grafana.com/cert-hash-tempo-tempostack-gateway-mtls: ecc05d82d5908bec73900b16748e1704a00db2d0aaff22bec4c53a19a05198d4
    tempo.grafana.com/cert-hash-tempo-tempostack-ingester-mtls: eb5bb257583f71728793234b0f4e23f9df63f7d66580f66eabcdf32280a5c14c
    tempo.grafana.com/cert-hash-tempo-tempostack-querier-mtls: 5287da60de9c1845222da9397051a7ae58ab632cf680f51605cacd77321cc727
    tempo.grafana.com/cert-hash-tempo-tempostack-query-frontend-mtls: 34e7cdc153b7f05cfc5d5c718ceb7c0c533a7917f46dd44295c4d89cb88d853c
  creationTimestamp: "2026-01-07T19:08:38Z"
  finalizers:
  - tempo.grafana.com/finalizer
  generation: 1
  labels:
    app.kubernetes.io/managed-by: tempo-operator
    tempo-perf-test.io/instance: tempo-perf-1x-small
    tempo-perf-test.io/managed-by: framework
    tempo.grafana.com/distribution: openshift
  name: tempostack
  namespace: tempo-perf-1x-small
  resourceVersion: "329926"
  uid: 3ddb261f-9bb7-44c8-9d03-cdf5fea4d23e
spec:
  extraConfig:
    tempo:
      ingester:
        max_block_duration: 10m
  hashRing:
    memberlist: {}
  images: {}
  limits:
    global:
      ingestion:
        maxTracesPerUser: 0
      query:
        maxSearchDuration: 0s
  managementState: Managed
  observability:
    grafana:
      instanceSelector: {}
    metrics:
      createPrometheusRules: true
      createServiceMonitors: true
    tracing:
      jaeger_agent_endpoint: localhost:6831
      otlp_http_endpoint: http://localhost:4320
  replicationFactor: 1
  resources: {}
  retention:
    global:
      traces: 48h0m0s
  search:
    defaultResultLimit: 20
    maxDuration: 0s
  serviceAccount: tempo-tempostack
  storage:
    secret:
      name: minio
      type: s3
    tls:
      enabled: false
  storageSize: 10Gi
  template:
    compactor:
      replicas: 1
    distributor:
      component:
        replicas: 1
      tls:
        enabled: false
    gateway:
      component:
        replicas: 1
      enabled: true
      ingress:
        route:
          termination: reencrypt
        type: route
      rbac:
        enabled: false
    ingester:
      replicas: 1
    querier:
      replicas: 1
    queryFrontend:
      component:
        replicas: 1
      jaegerQuery:
        enabled: true
        ingress:
          route: {}
        monitorTab:
          enabled: false
          prometheusEndpoint: ""
        servicesQueryDuration: 72h0m0s
        tempoQuery: {}
  tenants:
    authentication:
    - tenantId: tenant-1
      tenantName: tenant-1
    mode: openshift
  timeout: 30s
status:
  components:
    compactor:
      Running:
      - tempo-tempostack-compactor-69dd7bfbd9-xn65l
      - tempo-tempostack-compactor-8784f6758-mcdcn
    distributor:
      Running:
      - tempo-tempostack-distributor-f8ccf44b4-8554m
    gateway:
      Running:
      - tempo-tempostack-gateway-549464554d-gd2v8
    ingester:
      Running:
      - tempo-tempostack-ingester-0
    querier:
      Running:
      - tempo-tempostack-querier-7c777f757f-qtmj9
    queryFrontend:
      Running:
      - tempo-tempostack-query-frontend-8454dcd588-wtkff
  conditions:
  - lastTransitionTime: "2026-01-07T19:09:03Z"
    message: 'built in cert manager error: failed to add certificate hash annotations:
      Operation cannot be fulfilled on tempostacks.tempo.grafana.com "tempostack":
      the object has been modified; please apply your changes to the latest version
      and try again'
    reason: FailedReconciliation
    status: "False"
    type: Failed
  - lastTransitionTime: "2026-01-07T19:09:03Z"
    message: Some Tempo components are pending on dependencies
    reason: PendingComponents
    status: "False"
    type: Pending
  - lastTransitionTime: "2026-01-07T19:09:03Z"
    message: All components are operational
    reason: Ready
    status: "True"
    type: Ready
  operatorVersion: 0.19.0
  tempoVersion: 2.9.0
